data.img_h: 384
data.img_w: 512 
data.name: kitti_raw
data.img_pre_downsample_ratio: 7.875
data.num_seq_per_gpu: 4
data.per_gpu_batch_size: 32

data.num_tgt_views: 1
data.training_set_path: 

data.val_set_path: 
data.visible_point_count: 256 
data.num_workers: 4

data.rotation_pi_ratio: 3
data.is_exclude_views: true
lr.backbone_lr: 0.001
lr.decay_gamma: 0.1
lr.decay_steps: 5,10
lr.decoder_lr: 0.001
lr.weight_decay: 4.0e-05
model.backbone_normalization: true
model.decoder_normalization: true
model.pos_encoding_multires: 10
model.imagenet_pretrained: true
mpi.disparity_end: 0.001
mpi.disparity_start: 10
mpi.is_bg_depth_inf: false
mpi.num_bins_coarse: 128
mpi.num_bins_fine: 0
mpi.valid_mask_threshold: 2
mpi.fix_disparity: false
mpi.use_alpha: false 
loss.smoothness_lambda_v1: 0.0
loss.smoothness_gmin: 2.0
loss.smoothness_grad_ratio: 0.1
loss.smoothness_lambda_v2: 0.01
training.epochs: 15
training.eval_interval: 10000 
training.fine_tune: false
training.gpus: 0
training.pretrained_checkpoint_path: null
training.sample_interval: 30
training.src_rgb_blending: true
training.use_multi_scale: true
testing.frames_apart: random
data.img_h: 128
data.img_w: 384
data.name: kitti_raw
data.per_gpu_batch_size: 1
data.training_set_path: 
data.val_set_path: 
lr.backbone_lr: 0.001
lr.decay_gamma: 0.1
lr.decay_steps: 40,80,100
lr.decoder_lr: 0.001
lr.pan_lr: 0.0001
lr.weight_decay: 4.0e-05
mpi.disparity_end: 0.001
mpi.disparity_start: 1
training.epochs: 120 
training.eval_interval: 2000
training.gpus: 0
